[package]
name = "tagfs-core"
version = "0.1.0"
edition = "2024"

[dependencies]
file-id = "0.2.3"
jwalk = "0.8.1"
rusqlite = { version = "0.37.0", features = ["bundled"] }
serde_json = "1.0.145"
tempfile = "3.23.0"
thiserror = "2.0.17"
